#!/bin/sh
echo "danilothiago"
git config --global user.name "Danilo Thiago" --replace-all
git config --global user.email danilo.t.a.oliveira@hotmail.com --replace-all
git add --all
git commit -m 'next step'